#!/usr/bin/env bash
#doc

domain=$1
sub=$2
if ((sub)) then
	o="$(dig "${sub}.${domain}" | grep -C1 'ANSWER SECTION:'| tail -n1| rev | cut -f 1-2)"
	echo "The subdomain ${sub} is a $(echo "$o" | cut -f2) record and points to $(echo "$o" | cut -f1)"
else
	for sub in  www lb-01 web-01 web-02
	do
		o="$(dig "${sub}.${domain}" | grep -C1 'ANSWER SECTION:'| tail -n1| rev | cut -f 1-2)"
		echo "The subdomain ${sub} is a $(echo "$o" | cut -f2) record and points to $(echo "$o" | cut -f1)"
	done

fi
