#!/usr/bin/env bash
# doc

sudo apt-get -y update
sudo apt-get install nginx -y
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.nginx-debian.html
chown -R $USER:$USE /var/www/html/index.nginx-debian.txt
num=$(grep -Fn location /etc/nginx/sites-available/default | head -1 | cut -d":" -f1)
redirectStr="\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n\n"
echo "Ceci n'est pas une page" > /var/www/html/'404.html'
error_p="\n\terror_page 404 /404.html;\n"
sudo sed -i "$(($num - 1))s|.*|$redirectStr|" /etc/nginx/sites-available/default
sudo sed -i "$(($num - 1))s|.*|$error_p|" /etc/nginx/sites-available/default
sudo service nginx restart
