#!/usr/bin/env bash
#doc
sudo apt-get -y update
sudo apt-get -y install ufw

sudo sed -i 's/IPV6=no/IPV6=yes/g' /etc/default/ufw
sudo ufw default allow outgoing
sudo ufw default deny incoming
sudo ufw allow ssh
sudo ufw allow http
sudo ufw  allow https
sudo ufw enable
